name: ci

on:
  push:
    branches: master

jobs:
  build-qa-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: qa
          platforms: linux/amd64,linux/arm/v7
          push: true
          build-args: PHP_VERSION=7.4
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/test-gh-actions:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/test-gh-actions:1.0.0

  multi:
    needs: build-qa-image
    runs-on: ubuntu-latest
    container: ${{ secrets.DOCKERHUB_USERNAME }}/test-gh-actions:1.0.0
    steps:
      -
      name: phpunit
      run: ./vendor/bin/phpunit
